### PR TITLE
migrate from boxcutter -> bento/ubuntu-15.04 vagrant image

### PR DESCRIPTION
**Pull request by tejasmanohar**
`vagrant box add boxcutter/ubuntu1510` 404s. I could be missing something... let me know if so, but it seems bento/* is the official image from Hashicorp anyways.

### CODE REVIEW

**Comment by ejj** [comment]
Needs a better commit message.  Otherwise looks good.

**Comment by tejasmanohar** [comment]
@ejj Sounds fair. I will read doc & revise messages tonight. Gonna do some more testing on the bento image as well, as I was using trusty at first for testing w/ the IP parsing changes.

**Comment by kklin** [comment]
FYI @tejasmanohar, Vagrant was coincidentally fixed by upgrading to Ubuntu 16.04 (https://github.com/NetSys/quilt/pull/531/commits/d54aa02c03b591970803112b8a0210c3cd583305)

**Comment by tejasmanohar** [comment]
@kklin Yep. Same result. I didn't see your branch earlier, but looks like you have #529 as well so I'll close my PRs. Thanks!

**Pull request closed without merging**
