### PR TITLE
Table level locks on the db

### PR DESCRIPTION
**Pull request by mmussomele**

### CODE REVIEW

**Comment by ejj** [comment]
@mmussomele could you rebase?

**Comment by mmussomele** [comment]
Done and tested.

**Comment by mmussomele** [comment]
Not ready for merge; need to update the DB transaction convert commit to handle all the new transactions that have appeared since this PR was opened.

**Comment by ejj** [comment]
Closing for now -- when it's ready for review we can reopen the PR.

**Pull request closed without merging**
