### PR TITLE
Assorted Fixes

### PR DESCRIPTION
**Pull request by kklin**
These are the small tweaks from the paper branch, many of which are dependencies of future PR's.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Should this have been merged to `paper`, too?

**Comment by tejasmanohar** [comment]
FYI, I'm facing some issues after this PR. Looks like in some cases, Vagrant provider is not booted successfully, as I see logs like
```
INFO [Sep 28 02:36:36.624] Failed to retrieve IP address for 04351510-4404-4616-be87-715290fd8cba. error=exit status 1
ERROR [Sep 28 02:36:38.175] Failed to execute vagrant command: VM must be created before running this command. Run `vagrant up` first.
```
(logs from #536)

I'll take a peek later (likely tomorrow evening) but wanted to make note.

**Comment by kklin** [comment]
@tejasmanohar I didn't see that when testing, but our Vagrant backend has been pretty flaky in general (we use Amazon exclusively basically).

**Comment by ejj** [comment]
If you want to fix it though, that'd be awesome.  It'd definitely be useful, it's just been on the back burner while we tackle other priorities.

**Pull request merged**
