### PR TITLE
quilt: Add option for TLS for GRPC communication

### PR DESCRIPTION
**Pull request by kklin**
Before, we used insecure HTTP for our GRPC servers, which meant that
malicious parties could read our traffic, or even masquerade as the
controller and change specs at will.

This patch adds support for TLS mutual authentication for communicating
with the minion and daemon. If TLS is enabled, the minion servers boot
with a public, private key pair signed by a given certificate authority.
To connect, clients must have a key pair signed by the same CA.

Note that TLS must be explicitly enabled, so this patch will not affect
the current workflow.

### CODE REVIEW

**Comment by kklin** [comment]
Going to rebase this.

**Comment by kklin** [comment]
Rebased.

**Comment by kklin** [comment]
@mmussomele going to rebase this first, will ping you when ready (in a day or so).

**Comment by mmussomele** [comment]
@kklin any updates on the rebase?

**Comment by kklin** [comment]
Decided the code could be improved while rebasing, I'll reopen this later.

**Pull request closed without merging**
